// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         testid: "testid",
 *         field2: "field2"
 *     }
 */
export interface GetDbTestTestidTest2Field2Request {
    testid: string;
    field2: string;
}
