# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .error import Error
    from .pagination_metadata import PaginationMetadata
    from .test2get_response import Test2GetResponse
    from .test2post_response import Test2PostResponse
    from .test_get_response import TestGetResponse
    from .test_post_response import TestPostResponse
_dynamic_imports: typing.Dict[str, str] = {
    "Error": ".error",
    "PaginationMetadata": ".pagination_metadata",
    "Test2GetResponse": ".test2get_response",
    "Test2PostResponse": ".test2post_response",
    "TestGetResponse": ".test_get_response",
    "TestPostResponse": ".test_post_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Error",
    "PaginationMetadata",
    "Test2GetResponse",
    "Test2PostResponse",
    "TestGetResponse",
    "TestPostResponse",
]
