
DROP TABLE IF EXISTS test;
DROP TABLE IF EXISTS test2;

CREATE TABLE test (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  field1 TEXT UNIQUE NOT NULL,
  field2 TEXT NOT NULL
);

CREATE TABLE test2 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  test_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  field2 TEXT UNIQUE NOT NULL,
  field3 TEXT NOT NULL,
  FOREIGN KEY (test_id) REFERENCES test (id)
);
