# coding: utf-8

"""
    Test API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.generated3 import Generated3

class TestGenerated3(unittest.TestCase):
    """Generated3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Generated3:
        """Test Generated3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Generated3`
        """
        model = Generated3()
        if include_optional:
            return Generated3(
                field3 = ''
            )
        else:
            return Generated3(
                field3 = '',
        )
        """

    def testGenerated3(self):
        """Test Generated3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
