# coding: utf-8

"""
    Test API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.generated5 import Generated5

class TestGenerated5(unittest.TestCase):
    """Generated5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Generated5:
        """Test Generated5
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Generated5`
        """
        model = Generated5()
        if include_optional:
            return Generated5(
                id = 56,
                test_id = '',
                field2 = '',
                field3 = ''
            )
        else:
            return Generated5(
                test_id = '',
                field2 = '',
                field3 = '',
        )
        """

    def testGenerated5(self):
        """Test Generated5"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
