# coding: utf-8

# flake8: noqa

"""
    Test API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DbApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Error",
    "PaginationMetadata",
    "Test2GetResponse",
    "Test2PostRequestJson",
    "TestGetResponse",
    "TestPostRequestJson",
]

# import apis into sdk package
from openapi_client.api.db_api import DbApi as DbApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.error import Error as Error
from openapi_client.models.pagination_metadata import PaginationMetadata as PaginationMetadata
from openapi_client.models.test2_get_response import Test2GetResponse as Test2GetResponse
from openapi_client.models.test2_post_request_json import Test2PostRequestJson as Test2PostRequestJson
from openapi_client.models.test_get_response import TestGetResponse as TestGetResponse
from openapi_client.models.test_post_request_json import TestPostRequestJson as TestPostRequestJson

