# coding: utf-8

"""
    Test API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.generated import Generated

class TestGenerated(unittest.TestCase):
    """Generated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Generated:
        """Test Generated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Generated`
        """
        model = Generated()
        if include_optional:
            return Generated(
                field2 = ''
            )
        else:
            return Generated(
                field2 = '',
        )
        """

    def testGenerated(self):
        """Test Generated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
