# coding: utf-8

"""
    Test API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.test2_get_response import Test2GetResponse

class TestTest2GetResponse(unittest.TestCase):
    """Test2GetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Test2GetResponse:
        """Test Test2GetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Test2GetResponse`
        """
        model = Test2GetResponse()
        if include_optional:
            return Test2GetResponse(
                id = 56,
                test_id = '',
                created = '',
                field2 = '',
                field3 = ''
            )
        else:
            return Test2GetResponse(
                test_id = '',
                created = '',
                field2 = '',
                field3 = '',
        )
        """

    def testTest2GetResponse(self):
        """Test Test2GetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
