# coding: utf-8

"""
    Test API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.db_api import DbApi


class TestDbApi(unittest.TestCase):
    """DbApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DbApi()

    def tearDown(self) -> None:
        pass

    def test_db_test_field1_get(self) -> None:
        """Test case for db_test_field1_get

        """
        pass

    def test_db_test_field1_post(self) -> None:
        """Test case for db_test_field1_post

        """
        pass

    def test_db_test_testid_test2_field2_get(self) -> None:
        """Test case for db_test_testid_test2_field2_get

        """
        pass

    def test_db_test_testid_test2_field2_post(self) -> None:
        """Test case for db_test_testid_test2_field2_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
