// This file was auto-generated by Fern from our API Definition.

export interface Error_ {
    /** Error code */
    code?: number | undefined;
    /** Error message */
    message?: string | undefined;
    /** Errors */
    errors?: Record<string, unknown> | undefined;
    /** Error name */
    status?: string | undefined;
}
