// This file was auto-generated by Fern from our API Definition.

export interface PaginationMetadata {
    total?: number | undefined;
    total_pages?: number | undefined;
    first_page?: number | undefined;
    last_page?: number | undefined;
    page?: number | undefined;
    previous_page?: number | undefined;
    next_page?: number | undefined;
}
