// This file was auto-generated by Fern from our API Definition.

import { DbClient } from "./api/resources/db/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";

export declare namespace MineApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MineApiClient {
    protected readonly _options: NormalizedClientOptions<MineApiClient.Options>;
    protected _db: DbClient | undefined;

    constructor(options: MineApiClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get db(): DbClient {
        return (this._db ??= new DbClient(this._options));
    }
}
