# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawDbClient, RawDbClient


class DbClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDbClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDbClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDbClient
        """
        return self._raw_client

    def get_db_test_field1(self, field1: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        field1 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mine import MineApi

        client = MineApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.db.get_db_test_field1(
            field1="field1",
        )
        """
        _response = self._raw_client.get_db_test_field1(field1, request_options=request_options)
        return _response.data

    def post_db_test_field1(self, field1: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        field1 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mine import MineApi

        client = MineApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.db.post_db_test_field1(
            field1="field1",
        )
        """
        _response = self._raw_client.post_db_test_field1(field1, request_options=request_options)
        return _response.data

    def get_db_test_testid_test2field2(
        self, testid: str, field2: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mine import MineApi

        client = MineApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.db.get_db_test_testid_test2field2(
            testid="testid",
            field2="field2",
        )
        """
        _response = self._raw_client.get_db_test_testid_test2field2(testid, field2, request_options=request_options)
        return _response.data

    def post_db_test_testid_test2field2(
        self, testid: str, field2: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mine import MineApi

        client = MineApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.db.post_db_test_testid_test2field2(
            testid="testid",
            field2="field2",
        )
        """
        _response = self._raw_client.post_db_test_testid_test2field2(testid, field2, request_options=request_options)
        return _response.data


class AsyncDbClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDbClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDbClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDbClient
        """
        return self._raw_client

    async def get_db_test_field1(self, field1: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        field1 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mine import AsyncMineApi

        client = AsyncMineApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.db.get_db_test_field1(
                field1="field1",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_db_test_field1(field1, request_options=request_options)
        return _response.data

    async def post_db_test_field1(
        self, field1: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        field1 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mine import AsyncMineApi

        client = AsyncMineApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.db.post_db_test_field1(
                field1="field1",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_db_test_field1(field1, request_options=request_options)
        return _response.data

    async def get_db_test_testid_test2field2(
        self, testid: str, field2: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mine import AsyncMineApi

        client = AsyncMineApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.db.get_db_test_testid_test2field2(
                testid="testid",
                field2="field2",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_db_test_testid_test2field2(
            testid, field2, request_options=request_options
        )
        return _response.data

    async def post_db_test_testid_test2field2(
        self, testid: str, field2: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mine import AsyncMineApi

        client = AsyncMineApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.db.post_db_test_testid_test2field2(
                testid="testid",
                field2="field2",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_db_test_testid_test2field2(
            testid, field2, request_options=request_options
        )
        return _response.data
