# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.test2get_response import Test2GetResponse
from ..types.test2post_response import Test2PostResponse
from ..types.test_get_response import TestGetResponse
from ..types.test_post_response import TestPostResponse
from .raw_client import AsyncRawDbClient, RawDbClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DbClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDbClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDbClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDbClient
        """
        return self._raw_client

    def get_row_from_test(
        self, field1: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TestGetResponse:
        """
        Parameters
        ----------
        field1 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestGetResponse
            OK

        Examples
        --------
        from mine import MineApi

        client = MineApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.db.get_row_from_test(
            field1="field1",
        )
        """
        _response = self._raw_client.get_row_from_test(field1, request_options=request_options)
        return _response.data

    def add_row_into_test(
        self, field1: str, *, field2: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TestPostResponse:
        """
        Parameters
        ----------
        field1 : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestPostResponse
            OK

        Examples
        --------
        from mine import MineApi

        client = MineApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.db.add_row_into_test(
            field1="field1",
            field2="field2",
        )
        """
        _response = self._raw_client.add_row_into_test(field1, field2=field2, request_options=request_options)
        return _response.data

    def get_row_from_test2(
        self, testid: str, field2: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Test2GetResponse:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Test2GetResponse
            OK

        Examples
        --------
        from mine import MineApi

        client = MineApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.db.get_row_from_test2(
            testid="testid",
            field2="field2",
        )
        """
        _response = self._raw_client.get_row_from_test2(testid, field2, request_options=request_options)
        return _response.data

    def add_row_to_test2with_foreign_key_to_test(
        self, testid: str, field2: str, *, field3: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Test2PostResponse:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        field3 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Test2PostResponse
            OK

        Examples
        --------
        from mine import MineApi

        client = MineApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.db.add_row_to_test2with_foreign_key_to_test(
            testid="testid",
            field2="field2",
            field3="field3",
        )
        """
        _response = self._raw_client.add_row_to_test2with_foreign_key_to_test(
            testid, field2, field3=field3, request_options=request_options
        )
        return _response.data


class AsyncDbClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDbClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDbClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDbClient
        """
        return self._raw_client

    async def get_row_from_test(
        self, field1: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TestGetResponse:
        """
        Parameters
        ----------
        field1 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestGetResponse
            OK

        Examples
        --------
        import asyncio

        from mine import AsyncMineApi

        client = AsyncMineApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.db.get_row_from_test(
                field1="field1",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_row_from_test(field1, request_options=request_options)
        return _response.data

    async def add_row_into_test(
        self, field1: str, *, field2: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TestPostResponse:
        """
        Parameters
        ----------
        field1 : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestPostResponse
            OK

        Examples
        --------
        import asyncio

        from mine import AsyncMineApi

        client = AsyncMineApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.db.add_row_into_test(
                field1="field1",
                field2="field2",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_row_into_test(field1, field2=field2, request_options=request_options)
        return _response.data

    async def get_row_from_test2(
        self, testid: str, field2: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Test2GetResponse:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Test2GetResponse
            OK

        Examples
        --------
        import asyncio

        from mine import AsyncMineApi

        client = AsyncMineApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.db.get_row_from_test2(
                testid="testid",
                field2="field2",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_row_from_test2(testid, field2, request_options=request_options)
        return _response.data

    async def add_row_to_test2with_foreign_key_to_test(
        self, testid: str, field2: str, *, field3: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Test2PostResponse:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        field3 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Test2PostResponse
            OK

        Examples
        --------
        import asyncio

        from mine import AsyncMineApi

        client = AsyncMineApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.db.add_row_to_test2with_foreign_key_to_test(
                testid="testid",
                field2="field2",
                field3="field3",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_row_to_test2with_foreign_key_to_test(
            testid, field2, field3=field3, request_options=request_options
        )
        return _response.data
