# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.error import Error
from ..types.test2get_response import Test2GetResponse
from ..types.test2post_response import Test2PostResponse
from ..types.test_get_response import TestGetResponse
from ..types.test_post_response import TestPostResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawDbClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_row_from_test(
        self, field1: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[TestGetResponse]:
        """
        Parameters
        ----------
        field1 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TestGetResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"db/test/{jsonable_encoder(field1)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestGetResponse,
                    parse_obj_as(
                        type_=TestGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_row_into_test(
        self, field1: str, *, field2: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[TestPostResponse]:
        """
        Parameters
        ----------
        field1 : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TestPostResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"db/test/{jsonable_encoder(field1)}",
            method="POST",
            json={
                "field2": field2,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestPostResponse,
                    parse_obj_as(
                        type_=TestPostResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_row_from_test2(
        self, testid: str, field2: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Test2GetResponse]:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Test2GetResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"db/test/{jsonable_encoder(testid)}/test2/{jsonable_encoder(field2)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Test2GetResponse,
                    parse_obj_as(
                        type_=Test2GetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_row_to_test2with_foreign_key_to_test(
        self, testid: str, field2: str, *, field3: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Test2PostResponse]:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        field3 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Test2PostResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"db/test/{jsonable_encoder(testid)}/test2/{jsonable_encoder(field2)}",
            method="POST",
            json={
                "field3": field3,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Test2PostResponse,
                    parse_obj_as(
                        type_=Test2PostResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawDbClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_row_from_test(
        self, field1: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[TestGetResponse]:
        """
        Parameters
        ----------
        field1 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TestGetResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"db/test/{jsonable_encoder(field1)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestGetResponse,
                    parse_obj_as(
                        type_=TestGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_row_into_test(
        self, field1: str, *, field2: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[TestPostResponse]:
        """
        Parameters
        ----------
        field1 : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TestPostResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"db/test/{jsonable_encoder(field1)}",
            method="POST",
            json={
                "field2": field2,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestPostResponse,
                    parse_obj_as(
                        type_=TestPostResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_row_from_test2(
        self, testid: str, field2: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Test2GetResponse]:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Test2GetResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"db/test/{jsonable_encoder(testid)}/test2/{jsonable_encoder(field2)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Test2GetResponse,
                    parse_obj_as(
                        type_=Test2GetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_row_to_test2with_foreign_key_to_test(
        self, testid: str, field2: str, *, field3: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Test2PostResponse]:
        """
        Parameters
        ----------
        testid : str

        field2 : str

        field3 : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Test2PostResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"db/test/{jsonable_encoder(testid)}/test2/{jsonable_encoder(field2)}",
            method="POST",
            json={
                "field3": field3,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Test2PostResponse,
                    parse_obj_as(
                        type_=Test2PostResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
